/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as SearchRouteImport } from "./routes/search"
import { Route as RemoteRouteImport } from "./routes/remote"
import { Route as LibraryRouteImport } from "./routes/library"
import { Route as CollectionsRouteImport } from "./routes/collections"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as CollectionSplatRouteImport } from "./routes/collection.$"
import { Route as ArrowSplatRouteImport } from "./routes/arrow.$"

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteRoute = RemoteRouteImport.update({
  id: "/remote",
  path: "/remote",
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: "/library",
  path: "/library",
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: "/collections",
  path: "/collections",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSplatRoute = CollectionSplatRouteImport.update({
  id: "/collection/$",
  path: "/collection/$",
  getParentRoute: () => rootRouteImport,
} as any)
const ArrowSplatRoute = ArrowSplatRouteImport.update({
  id: "/arrow/$",
  path: "/arrow/$",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/collections": typeof CollectionsRoute
  "/library": typeof LibraryRoute
  "/remote": typeof RemoteRoute
  "/search": typeof SearchRoute
  "/settings": typeof SettingsRoute
  "/arrow/$": typeof ArrowSplatRoute
  "/collection/$": typeof CollectionSplatRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/collections": typeof CollectionsRoute
  "/library": typeof LibraryRoute
  "/remote": typeof RemoteRoute
  "/search": typeof SearchRoute
  "/settings": typeof SettingsRoute
  "/arrow/$": typeof ArrowSplatRoute
  "/collection/$": typeof CollectionSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/collections": typeof CollectionsRoute
  "/library": typeof LibraryRoute
  "/remote": typeof RemoteRoute
  "/search": typeof SearchRoute
  "/settings": typeof SettingsRoute
  "/arrow/$": typeof ArrowSplatRoute
  "/collection/$": typeof CollectionSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/collections"
    | "/library"
    | "/remote"
    | "/search"
    | "/settings"
    | "/arrow/$"
    | "/collection/$"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/collections"
    | "/library"
    | "/remote"
    | "/search"
    | "/settings"
    | "/arrow/$"
    | "/collection/$"
  id:
    | "__root__"
    | "/"
    | "/collections"
    | "/library"
    | "/remote"
    | "/search"
    | "/settings"
    | "/arrow/$"
    | "/collection/$"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  LibraryRoute: typeof LibraryRoute
  RemoteRoute: typeof RemoteRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ArrowSplatRoute: typeof ArrowSplatRoute
  CollectionSplatRoute: typeof CollectionSplatRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/search": {
      id: "/search"
      path: "/search"
      fullPath: "/search"
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/remote": {
      id: "/remote"
      path: "/remote"
      fullPath: "/remote"
      preLoaderRoute: typeof RemoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/library": {
      id: "/library"
      path: "/library"
      fullPath: "/library"
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/collections": {
      id: "/collections"
      path: "/collections"
      fullPath: "/collections"
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/collection/$": {
      id: "/collection/$"
      path: "/collection/$"
      fullPath: "/collection/$"
      preLoaderRoute: typeof CollectionSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/arrow/$": {
      id: "/arrow/$"
      path: "/arrow/$"
      fullPath: "/arrow/$"
      preLoaderRoute: typeof ArrowSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  LibraryRoute: LibraryRoute,
  RemoteRoute: RemoteRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ArrowSplatRoute: ArrowSplatRoute,
  CollectionSplatRoute: CollectionSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
